services:
  - type: web
    name: ionic-app
    env: static
    staticPublishPath: www
    buildCommand: npm run build -- --configuration production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
